name: Deploy to Pantheon
on:
  push:
    branches:
      - 'dev-build'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        echo "repo :: ${{ secrets.PANTHEON_REPO }}" . $pantheon_repo
        echo "keys2 :: ${{ secrets.PANTHEON_SSH_KEY }}" . $key
        git remote add pantheon $pantheon_repo
        git push -f pantheon dev-build 
